<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.bookcompanion</groupId>
  <artifactId>orders-learning</artifactId>
  <version>2.0.0</version>
  <packaging>mule-application</packaging>
  <properties>
    <app.runtime>4.12.3</app.runtime>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <build><plugins>
    <plugin>
      <groupId>org.mule.tools.maven</groupId>
      <artifactId>mule-maven-plugin</artifactId>
      <version>4.10.0</version>
      <extensions>true</extensions>
      <configuration>
        <skipAST>true</skipAST>
        <sharedLibraries><sharedLibrary><groupId>com.h2database</groupId><artifactId>h2</artifactId></sharedLibrary></sharedLibraries>
      </configuration>
    </plugin>

  </plugins></build>
  <dependencies>
    <dependency>
      <groupId>org.mule.connectors</groupId>
      <artifactId>mule-http-connector</artifactId>
      <version>1.11.3</version>
      <classifier>mule-plugin</classifier>
    </dependency>
    <dependency>
      <groupId>org.mule.connectors</groupId>
      <artifactId>mule-db-connector</artifactId>
      <version>1.15.1</version>
      <classifier>mule-plugin</classifier>
    </dependency>
    <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
      <version>2.3.232</version>
    </dependency>
    <dependency>
      <groupId>org.mule.modules</groupId>
      <artifactId>mule-apikit-module</artifactId>
      <version>1.11.17</version>
      <classifier>mule-plugin</classifier>
    </dependency>
  </dependencies>
  <repositories><repository><id>mulesoft-releases</id><url>https://repository.mulesoft.org/releases/</url></repository></repositories>
  <pluginRepositories><pluginRepository><id>mulesoft-releases</id><url>https://repository.mulesoft.org/releases/</url></pluginRepository></pluginRepositories>
</project>
